## Data

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data/survey_results_public.csv", index_col="Respondent")
schema_df = pd.read_csv("data/survey_results_schema.csv", index_col="Column")

In [3]:
df.rename(columns={"ConvertedComp":"Salary"}, inplace=True)

## Grouping

Gruplama bir kaç adımdan oluşur. Bunlar:

1) Elimizdeki veriyi farklı kırılımlara göre bölmek

2) İstenen fonksiyonu uygulamak

3) Bölünen parçaları yeniden birleştirmek

In [ ]:
#gruplama iki aşamadan oluşur. grupların üzerine uygulayacağın fonksiyonu belirtirsin.

In [7]:
df

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",...,NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [8]:
df.columns

Index(['MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource', 'Employment',
       'Country', 'Student', 'EdLevel', 'UndergradMajor', 'EduOther',
       'OrgSize', 'DevType', 'YearsCode', 'Age1stCode', 'YearsCodePro',
       'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney', 'MgrWant', 'JobSeek',
       'LastHireDate', 'LastInt', 'FizzBuzz', 'JobFactors', 'ResumeUpdate',
       'CurrencySymbol', 'CurrencyDesc', 'CompTotal', 'CompFreq', 'Salary',
       'WorkWeekHrs', 'WorkPlan', 'WorkChallenge', 'WorkRemote', 'WorkLoc',
       'ImpSyn', 'CodeRev', 'CodeRevHrs', 'UnitTests', 'PurchaseHow',
       'PurchaseWhat', 'LanguageWorkedWith', 'LanguageDesireNextYear',
       'DatabaseWorkedWith', 'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'WebFrameWorkedWith',
       'WebFrameDesireNextYear', 'MiscTechWorkedWith',
       'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers',
       'BlockchainOrg', 'BlockchainIs', 'BetterLife', 'ITperson', 'OffOn',
       'SocialMedia', 'Extraversion', 'ScreenName', 'SOVisit1st',
       'SOVisitFreq', 'SOVisitTo', 'SOFindAnswer', 'SOTimeSaved',
       'SOHowMuchTime', 'SOAccount', 'SOPartFreq', 'SOJobs', 'EntTeams',
       'SOComm', 'WelcomeChange', 'SONewContent', 'Age', 'Gender', 'Trans',
       'Sexuality', 'Ethnicity', 'Dependents', 'SurveyLength', 'SurveyEase'],
      dtype='object')

In [9]:
df["Country"]

Respondent
1                United Kingdom
2        Bosnia and Herzegovina
3                      Thailand
4                 United States
5                       Ukraine
                  ...
88377                    Canada
88601                       NaN
88802                       NaN
88816                       NaN
88863                     Spain
Name: Country, Length: 88883, dtype: object

In [10]:
df["Country"].value_counts() #179 ülke

United States                       20949
India                                9061
Germany                              5866
United Kingdom                       5737
Canada                               3395
                                    ...
North Korea                             1
Tonga                                   1
Papua New Guinea                        1
Niger                                   1
Saint Vincent and the Grenadines        1
Name: Country, Length: 179, dtype: int64

In [11]:
df.groupby(["Country"])

## Splitting

In [4]:
country_group = df.groupby(["Country"]) #groupby ile gruplama yaparız. countrye göre grupla. 
                                        #arka planda 179 data dataframe oluşturmuyor şemasını çıkartıyor. hayali bir durum çıkartıyor.

In [5]:
country_group #bana bunu series olarak döndürür.

In [6]:
# Sadece "Country" sütununda Turkey olanları döndürür
country_group.get_group("Turkey") # df[df["Country"] == "Turkey"]

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,
28,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,Turkey,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","A business discipline (ex. accounting, finance...",Taken an online course in programming or softw...,...,NaN,NaN,NaN,Man,No,NaN,NaN,NaN,NaN,NaN
123,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,Turkey,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...",Taken an online course in programming or softw...,...,A lot more welcome now than last year,Tech articles written by other developers;Indu...,24.0,Man,No,Bisexual,NaN,No,Too long,Easy
240,I am a student who is learning to code,Yes,Never,"OSS is, on average, of LOWER quality than prop...","Not employed, and not looking for work",Turkey,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,...,A lot more welcome now than last year,Tech articles written by other developers;Indu...,21.0,Man,No,Straight / Heterosexual,NaN,No,Too long,Neither easy nor difficult
635,I am a developer by profession,No,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",Turkey,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",Mathematics or statistics,Taken an online course in programming or softw...,...,Somewhat less welcome now than last year,NaN,36.0,Woman,No,NaN,White or of European descent,Yes,Appropriate in length,Difficult
673,I code primarily as a hobby,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Turkey,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",...,Somewhat more welcome now than last year,Tech articles written by other developers;Indu...,13.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88819,I am a student who is learning to code,Yes,Less than once per year,The quality of OSS and closed source software ...,"Independent contractor, freelancer, or self-em...",Turkey,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88844,I am a developer by profession,No,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Turkey,"Yes, full-time","Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Somewhat more welcome now than last year,NaN,36.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Too long,Easy
88846,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,Turkey,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","A business discipline (ex. accounting, finance...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,25.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
25205,NaN,Yes,Once a month or more often,"OSS is, on average, of LOWER quality than prop...",Employed full-time,Turkey,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,A lot more welcome now than last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
48134,NaN,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,Turkey,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...",Taken an online course in programming or softw...,...,NaN,NaN,36.0,Man,No,Straight / Heterosexual,Middle Eastern;White or of European descent,Yes,Too long,Difficult

In [15]:
type(country_group.get_group("Turkey"))

pandas.core.frame.DataFrame

In [8]:
country_group.get_group("Germany")

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,
14,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,Germany,No,"Other doctoral degree (Ph.D, Ed.D., etc.)","Computer science, computer engineering, or sof...",Completed an industry certification program (e...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Cour...,31.0,Man,No,Straight / Heterosexual,White or of European descent,No,Too short,Easy
36,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,Germany,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,...,Somewhat less welcome now than last year,NaN,21.0,Man,No,Straight / Heterosexual,White or of European descent,No,Too long,Neither easy nor difficult
44,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,Germany,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,43.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
66,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Germany,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Too long,Neither easy nor difficult
85,I am a developer by profession,Yes,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",Germany,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Somewhat less welcome now than last year,Tech articles written by other developers;Tech...,31.0,Man,No,Straight / Heterosexual,White or of European descent,NaN,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64465,NaN,Yes,Less than once per year,The quality of OSS and closed source software ...,NaN,Germany,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","A business discipline (ex. accounting, finance...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,NaN,NaN,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
71055,NaN,Yes,Never,"OSS is, on average, of LOWER quality than prop...","Not employed, and not looking for work",Germany,No,NaN,"A social science (ex. anthropology, psychology...",Contributed to open source software,...,A lot more welcome now than last year,Industry news about technologies you're intere...,2.0,Man,NaN,NaN,NaN,NaN,Too long,Difficult
75974,NaN,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Germany,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...","Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Industry news about technologies you're intere...,NaN,Man,No,NaN,Middle Eastern,Yes,Appropriate in length,Easy
80319,NaN,Yes,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",Germany,No,"Secondary school (e.g. American high school, G...",NaN,"Taught yourself a new language, framework, or ...",...,Somewhat more welcome now than last year,Tech articles written by other developers;Tech...,18.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Easy
83786,NaN,No,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,Germany,No,"Other doctoral degree (Ph.D, Ed.D., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,57.0,Man,No,NaN,White or of European descent,Yes,Too long,Neither easy nor difficult

In [ ]:

country_group.get_group("India")

**Yapılan şey bununla aynı:**

In [ ]:
filt = df["Country"] == "Turkey"

In [ ]:
df.loc[filt]

## Fonksiyon Uygulamak

**Ülkelere Göre Bölünmüş Median maaş**

In [10]:
country_group = df.groupby(["Country"]) #ülkelerin maaşların medyanlarıı

In [11]:
country_group["Salary"].median() #alttaki tablo bir seriesdir.

Country
Afghanistan                               6222.0
Albania                                  10818.0
Algeria                                   7878.0
Andorra                                 160931.0
Angola                                    7764.0
                                          ...
Venezuela, Bolivarian Republic of...      6384.0
Viet Nam                                 11892.0
Yemen                                    11940.0
Zambia                                    5040.0
Zimbabwe                                 19200.0
Name: Salary, Length: 179, dtype: float64

In [13]:
country_group["Salary"].median().sort_values(ascending = False)

Country
Liechtenstein                       811188.0
San Marino                          301788.0
Timor-Leste                         229500.0
Andorra                             160931.0
Democratic Republic of the Congo    110484.0
                                      ...
Papua New Guinea                         NaN
Saint Kitts and Nevis                    NaN
Sao Tome and Principe                    NaN
Sierra Leone                             NaN
Tonga                                    NaN
Name: Salary, Length: 179, dtype: float64

In [35]:
country_group["Salary"].median()["United States"]

110000.0

In [36]:
median_country = country_group["Salary"].median()#yukarıdakileri yazmak yerine median country e eşitle. bu daha basit...

In [37]:
median_country["Turkey"]

17280.0

In [38]:
median_country["Germany"]

63016.0

### Ülkelere Göre Sosyal Medya Popülerlik

In [17]:
filt = df["Country"] == "Turkey"

In [18]:
df_tr = df.loc[filt]

In [20]:
df_tr["SocialMedia"]

Respondent
28                      Instagram
123                      WhatsApp
240                      WhatsApp
635      I don't use social media
673                       YouTube
                   ...
88819                     YouTube
88844                    LinkedIn
88846                      Reddit
25205                   Instagram
48134                     Twitter
Name: SocialMedia, Length: 949, dtype: object

In [21]:
df_tr["SocialMedia"].value_counts()

WhatsApp                    233
Twitter                     167
YouTube                     156
Instagram                   117
Reddit                       98
LinkedIn                     73
I don't use social media     41
Facebook                     29
Youku Tudou 优酷                1
Name: SocialMedia, dtype: int64

* Bunun aynısını groupby ile de yapabiliriz

In [14]:
country_group = df.groupby(["Country"])

In [15]:
country_group["SocialMedia"]

In [24]:
country_group["SocialMedia"].value_counts()

Country      SocialMedia
Afghanistan  Facebook                    15
             YouTube                      9
             I don't use social media     6
             WhatsApp                     4
             Instagram                    1
                                         ..
Zimbabwe     Facebook                     3
             YouTube                      3
             Instagram                    2
             LinkedIn                     2
             Reddit                       1
Name: SocialMedia, Length: 1220, dtype: int64

In [25]:
type(country_group["SocialMedia"].value_counts())

pandas.core.series.Series

In [26]:
country_group["SocialMedia"].value_counts()["Turkey"]

SocialMedia
WhatsApp                    233
Twitter                     167
YouTube                     156
Instagram                   117
Reddit                       98
LinkedIn                     73
I don't use social media     41
Facebook                     29
Youku Tudou 优酷                1
Name: SocialMedia, dtype: int64

In [27]:
social_media_country = country_group["SocialMedia"].value_counts()

In [28]:
social_media_country["Germany"]

SocialMedia
WhatsApp                    1343
YouTube                      970
Reddit                       923
Twitter                      866
I don't use social media     501
Facebook                     404
Instagram                    264
LinkedIn                     141
Snapchat                      10
VK ВКонта́кте                  8
WeChat 微信                      8
Name: SocialMedia, dtype: int64

### agg()

Birden çok fonksiyon uygulamak istiyorsak

In [ ]:
#agg() diye bir fonksiyon var.
#birden çok series dataframe oluşturur.

In [22]:
country_group["Salary"].agg(["median", "mean"])

                                        median           mean
Country
Afghanistan                             6222.0  101953.333333
Albania                                10818.0   21833.700000
Algeria                                 7878.0   34924.047619
Andorra                               160931.0  160931.000000
Angola                                  7764.0    7764.000000
...                                        ...            ...
Venezuela, Bolivarian Republic of...    6384.0   14581.627907
Viet Nam                               11892.0   17233.436782
Yemen                                  11940.0   16909.166667
Zambia                                  5040.0   10075.375000
Zimbabwe                               19200.0   34046.666667

[179 rows x 2 columns]

In [23]:
country_group["Salary"].agg(["median", "mean"]).loc[["Turkey", "Germany"]]

          median           mean
Country
Turkey   17280.0   25133.222664
Germany  63016.0  109256.884066

In [40]:
type(country_group["Salary"].agg(["median", "mean"]))

pandas.core.frame.DataFrame

In [41]:
country_group["Salary"].agg(["median", "mean"]).loc["Germany"]

median     63016.000000
mean      109256.884066
Name: Germany, dtype: float64

In [42]:
type(country_group["Salary"].agg(["median", "mean"]).loc["Germany"])

pandas.core.series.Series

In [4]:
hobby_group = df.groupby(["Hobbyist"])

In [5]:
hobby_group["Salary"].agg(["median", "mean"])

           median           mean
Hobbyist
No        55000.0  126080.793095
Yes       57287.0  127380.459401